version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "32768:4160"
      - "32769:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
#    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1:4150
    depends_on:
      - nsqlookupd
    ports:
      - "32770:4150"
      - "32771:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "32772:4171"

  mongo:
    image: mongo:4.4.2
    ports:
      - "32773:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
